(()=>{'use strict';const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),fmt=(v,d=2)=>Number(v).toLocaleString(undefined,{maximumFractionDigits:d});

// Main technology tabs
const tabs=document.querySelectorAll('.tab'),views=document.querySelectorAll('.view');tabs.forEach(b=>b.addEventListener('click',()=>{tabs.forEach(x=>x.classList.remove('active'));views.forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active')}));

// First-order mesh physics screening model
const P={freq:$('freq'),spl:$('spl'),angle:$('angle'),diameter:$('diameter'),spacing:$('spacing')};
function updatePhysics(){if(!P.freq)return;const f=+P.freq.value,spl=+P.spl.value,a=+P.angle.value,D=+P.diameter.value,d=+P.spacing.value;[$('freqText'),$('splText'),$('angleText'),$('diameterText'),$('spacingText')].forEach((el,i)=>{if(!el)return;el.textContent=[f,spl,a,D.toFixed(1),d][i]});const rho=1025,c=1500,mu=.001,p=1e-6*Math.pow(10,spl/20),v=p/(rho*c),pen=Math.sqrt(mu/(Math.PI*rho*f)),fiber=2.7*Math.pow(D/6,2)*(20/d),proj=Math.abs(Math.cos(a*Math.PI/180)),def=.3*(fiber/2.7)*p*proj,q=(c/f)/4;$('pressureOut').textContent=p<.01?p.toExponential(2):fmt(p,3);$('velocityOut').textContent=fmt(v*1e9,3);$('penetrationOut').textContent=fmt(pen*1e6,1);$('deflectionOut').textContent=def<.001?fmt(def*1000,3)+' pm':fmt(def,4)+' nm';$('arraySpanSvg').textContent='¼λ ≈ '+fmt(q,2)+' m @ '+f+' Hz';$('fiberSvg').textContent='MESH FIBER ≈ '+fmt(fiber,2)+' m';$('directionSvg').textContent='PROJECTED RESPONSE ≈ '+fmt(proj*100,0)+'%';let n='At '+f+' Hz, wavelength in seawater is approximately '+fmt(c/f,1)+' m. A compact vector sensor is attractive where directional information is needed without relying only on a wavelength-scale aperture. At '+a+'° incidence, the simplified directional projection retains about '+fmt(proj*100,0)+'% of ideal response. ';n+=(pen*1e6>3.6?'The viscous penetration depth remains above the published prototype beam-width scale.':'The viscous length scale is approaching the published beam-width scale; the simplified model is increasingly uncertain.');$('modelInterpretation').textContent=n}
Object.values(P).forEach(x=>x&&x.addEventListener('input',updatePhysics));updatePhysics();

// Patent architecture switcher
const modes={base:['Floating-base architecture','Multiple directional flow meters are carried by a floating structure coupled to an anchor or lower assembly. Relative motion between the structure and surrounding fluid provides a path to local particle-motion sensing.'],tower:['Viscous-liquid channel tower','The continuation-in-part introduces differently oriented viscous-liquid channels, sensing cavities, onboard power, memory, telemetry, anchoring and detachable recovery embodiments.'],hull:['Platform integration concept','An OEM sensing module can be considered for UUV, hull, tow-body or fixed-node integration. Platform vibration, hydrodynamic flow noise, packaging and calibration become the dominant engineering risks.']};
const mb=document.querySelectorAll('.mode');function setMode(m){mb.forEach(b=>b.classList.toggle('active',b.dataset.mode===m));['base','tower','hull'].forEach(x=>{const e=$(x+'Diagram');if(e)e.style.display=x===m?'block':'none'});if($('modeTitle'))$('modeTitle').textContent=modes[m][0];if($('modeDescription'))$('modeDescription').textContent=modes[m][1]}mb.forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));setMode('base');

// Commercial opportunity screen
const opps=[['ASW sonobuoy / distributed sensing',9.4,'Direct low-frequency directional-sensing fit; strongest defense transition thesis.','Navy / primes / OEMs'],['UUV / AUV acoustic payload',8.8,'High value if compact directionality survives platform self-noise and flow.','UUV programs / robotics'],['Port + subsea surveillance',8.3,'Persistent directional nodes for vessel, machinery and infrastructure signatures.','Bases / ports / operators'],['Directional environmental PAM',7.9,'Bearing can add source-location context to passive acoustic monitoring.','NOAA ecosystem / offshore'],['Offshore source localization',7.2,'Relevant for machinery and subsea events; mature incumbents raise the bar.','Energy / inspection'],['Geophysical acquisition',6.8,'Low-frequency relevance, but established geophone and seabed-node markets.','Survey / seismic OEMs'],['Underwater communications RX',6.5,'Vector reception can reject interference; competitive MEMS/vector landscape.','Modem / AUV OEMs'],['In-air industrial acoustics',4.8,'Prototype evidence exists, but compact particle-velocity sensing is established.','Instrumentation']];
const list=$('opportunityList');if(list){opps.forEach((o,i)=>{const r=document.createElement('div');r.className='op';r.innerHTML='<div class="rank">0'+(i+1)+'</div><div class="name">'+o[0]+'</div><div class="why">'+o[2]+'</div><div class="buyer">'+o[3]+'</div><div class="score">'+o[1].toFixed(1)+'/10<div class="scorebar"><span style="width:'+(o[1]*10)+'%"></span></div></div>';list.appendChild(r)})}

// Mission demonstrator -------------------------------------------------------
const M={target:$('targetType'),config:$('sensorConfig'),freq:$('missionFreq'),range:$('missionRange'),bearing:$('missionBearing'),source:$('missionSource'),noise:$('missionNoise')};
let running=true,phase=0,last=performance.now();
const presets={surface:{target:'surface',config:'floating',freq:180,range:3.2,bearing:62,source:146,noise:82},submerged:{target:'submarine',config:'tower',freq:90,range:5.1,bearing:218,source:138,noise:78},monitor:{target:'surface',config:'platform',freq:240,range:1.8,bearing:315,source:132,noise:84}};
function setVal(id,v){const el=$(id);if(el){el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}))}}
function applyPreset(name){const p=presets[name];if(!p)return;M.target.value=p.target;M.config.value=p.config;setVal('missionFreq',p.freq);setVal('missionRange',p.range);setVal('missionBearing',p.bearing);setVal('missionSource',p.source);setVal('missionNoise',p.noise);document.querySelectorAll('.scenario-btn').forEach(b=>b.classList.toggle('active',b.dataset.scenario===name));updateMission()}
document.querySelectorAll('.scenario-btn').forEach(b=>b.addEventListener('click',()=>applyPreset(b.dataset.scenario)));

function configLabel(v){return v==='floating'?'Floating base / orthogonal meters':v==='tower'?'Viscous-channel tower':'Platform-integrated module'}
function targetLabel(v){return v==='surface'?'Surface vessel':v==='submarine'?'Submerged vessel':'Acoustic source'}
function missionMath(){const f=+M.freq.value,rkm=+M.range.value,b=+M.bearing.value,sl=+M.source.value,nl=+M.noise.value,rm=Math.max(1,rkm*1000),rho=1025,c=1500;const absorption=.00035*Math.pow(f/100,2);const tl=20*Math.log10(rm)+absorption*rkm;const rl=sl-tl;const snr=rl-nl;const pressure=1e-6*Math.pow(10,rl/20);const velocity=pressure/(rho*c);const theta=b*Math.PI/180;const vx=velocity*Math.sin(theta),vy=velocity*Math.cos(theta);const mesh=.3*pressure;const confidence=clamp(18+3.4*(snr+6),8,98);const error=clamp(30*Math.exp(-Math.max(snr,-5)/11),1.2,38);return{f,rkm,b,sl,nl,tl,rl,snr,pressure,velocity,vx,vy,mesh,confidence,error,wavelength:c/f}}
function setText(id,text){const e=$(id);if(e)e.textContent=text}
function updateTargetGraphic(type){const ship=$('surfaceTarget'),sub=$('subTarget'),src=$('sourceTarget');if(ship)ship.style.display=type==='surface'?'block':'none';if(sub)sub.style.display=type==='submarine'?'block':'none';if(src)src.style.display=type==='source'?'block':'none'}
function updateSensorGraphic(config){['floatingSensor','towerSensor','platformSensor'].forEach(id=>{const e=$(id);if(e)e.style.display='none'});const map={floating:'floatingSensor',tower:'towerSensor',platform:'platformSensor'};const e=$(map[config]);if(e)e.style.display='block'}
function updateMission(){if(!M.freq)return;const x=missionMath();setText('missionFreqText',x.f+' Hz');setText('missionRangeText',x.rkm.toFixed(1)+' km');setText('missionBearingText',Math.round(x.b)+'°');setText('missionSourceText',Math.round(x.sl)+' dB');setText('missionNoiseText',Math.round(x.nl)+' dB');setText('targetLabel',targetLabel(M.target.value));setText('configLabel',configLabel(M.config.value));setText('receivedLevel',x.rl.toFixed(1)+' dB');setText('missionSNR',(x.snr>=0?'+':'')+x.snr.toFixed(1)+' dB');setText('particleMotion',x.velocity<1e-9?(x.velocity*1e12).toFixed(2)+' pm/s':(x.velocity*1e9).toFixed(2)+' nm/s');setText('meshResponse',x.mesh<.001?(x.mesh*1000).toFixed(3)+' pm':x.mesh.toFixed(3)+' nm');setText('bearingEstimate',Math.round(x.b)+'° ± '+x.error.toFixed(1)+'°');setText('missionConfidence',Math.round(x.confidence)+'%');setText('wavelengthReadout',x.wavelength.toFixed(1)+' m');setText('missionTL',x.tl.toFixed(1)+' dB');const cb=$('confidenceBar');if(cb)cb.style.width=x.confidence+'%';const va=$('vectorArrow');if(va){va.style.transform='rotate('+(x.b-90)+'deg)';va.style.width=(26+52*x.confidence/100)+'px'};updateTargetGraphic(M.target.value);updateSensorGraphic(M.config.value);drawMission(x)}
Object.values(M).forEach(e=>e&&e.addEventListener('input',updateMission));if(M.target)M.target.addEventListener('change',updateMission);if(M.config)M.config.addEventListener('change',updateMission);

function drawMission(x){const cx=400,cy=300,maxRange=8.5,rad=245,rr=clamp(x.rkm/maxRange,0,.98)*rad,ang=x.b*Math.PI/180,tx=cx+rr*Math.sin(ang),ty=cy-rr*Math.cos(ang);const t=$('targetGroup');if(t)t.setAttribute('transform','translate('+tx+' '+ty+') rotate('+x.b+')');const trueLine=$('trueBearingLine');if(trueLine){trueLine.setAttribute('x1',cx);trueLine.setAttribute('y1',cy);trueLine.setAttribute('x2',tx);trueLine.setAttribute('y2',ty)}const uncertainty=$('bearingCone');if(uncertainty){const a1=(x.b-x.error)*Math.PI/180,a2=(x.b+x.error)*Math.PI/180,r=235,x1=cx+r*Math.sin(a1),y1=cy-r*Math.cos(a1),x2=cx+r*Math.sin(a2),y2=cy-r*Math.cos(a2);uncertainty.setAttribute('d','M '+cx+' '+cy+' L '+x1+' '+y1+' A '+r+' '+r+' 0 0 1 '+x2+' '+y2+' Z');uncertainty.setAttribute('opacity',String(clamp(.34-x.confidence*.0025,.07,.3)))}const north=$('northBearing');if(north)north.textContent=('000'+Math.round(x.b)).slice(-3)+'°';const rangeLbl=$('stageRangeLabel');if(rangeLbl){rangeLbl.setAttribute('x',tx+16);rangeLbl.setAttribute('y',ty-15);rangeLbl.textContent=x.rkm.toFixed(1)+' km'}const targetTxt=$('stageTargetLabel');if(targetTxt){targetTxt.setAttribute('x',tx+16);targetTxt.setAttribute('y',ty+3);targetTxt.textContent=targetLabel(M.target.value).toUpperCase()}const rings=document.querySelectorAll('.wave-ring');rings.forEach((r,i)=>{r.setAttribute('cx',tx);r.setAttribute('cy',ty)});const sx=$('sensorXbar'),sy=$('sensorYbar');if(sx){const norm=Math.min(1,Math.abs(x.vx)/(Math.abs(x.vx)+Math.abs(x.vy)+1e-18));sx.setAttribute('width',String(75*norm));sx.setAttribute('x',x.vx>=0?'400':String(400-75*norm))}if(sy){const norm=Math.min(1,Math.abs(x.vy)/(Math.abs(x.vx)+Math.abs(x.vy)+1e-18));sy.setAttribute('height',String(75*norm));sy.setAttribute('y',x.vy>=0?String(300-75*norm):'300')}}

function animate(now){const dt=(now-last)/1000;last=now;if(running)phase=(phase+dt*.28)%1;const rings=document.querySelectorAll('.wave-ring');rings.forEach((r,i)=>{const q=(phase+i/4)%1;r.setAttribute('r',String(18+96*q));r.setAttribute('opacity',String(.42*(1-q)))});const scan=$('scanLine');if(scan){const a=(now*.018)%360;scan.setAttribute('transform','rotate('+a+' 400 300)')}requestAnimationFrame(animate)}
const runBtn=$('runMission');if(runBtn)runBtn.addEventListener('click',()=>{running=!running;runBtn.textContent=running?'Pause animation':'Resume animation';runBtn.classList.toggle('primary',running)});const resetBtn=$('resetMission');if(resetBtn)resetBtn.addEventListener('click',()=>applyPreset('surface'));
applyPreset('surface');requestAnimationFrame(animate);
})();